# Generated by Django 6.0.2 on 2026-02-14 11:36

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('file', 'File'), ('folder', 'Folder')], max_length=6)),
                ('is_public', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('UPLOADING', 'Uploading'), ('ACTIVE', 'Active'), ('TRASHED', 'Trashed'), ('DRAFT', 'Draft')], db_index=True, default='UPLOADING', max_length=10)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('edit_node', 'Can edit the node, view, change, add, delete node')],
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='NodeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version_number', models.PositiveSmallIntegerField()),
                ('storage_provider', models.CharField(choices=[('azure', 'Azure Blob Storage'), ('aws', 'AWS S3'), ('local', 'Local Storage')], default='azure', max_length=128)),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('size', models.PositiveBigIntegerField(help_text='Size of the file in bytes')),
                ('mime_type', models.CharField(help_text='The IANA media type of the file', max_length=124)),
                ('checksum', models.CharField(help_text='MD5 hash of the file', max_length=64)),
                ('status', models.CharField(choices=[('UPLOADING', 'Uploading'), ('ACTIVE', 'Active'), ('FAILED', 'Failed')], db_index=True, default='UPLOADING', max_length=10)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='drive.node')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='node',
            name='current_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_version', to='drive.nodeversion'),
        ),
        migrations.CreateModel(
            name='StorageUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_bytes', models.PositiveBigIntegerField(default=0, help_text='Cumulative file sizes in bytes')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_usage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='tags',
            field=models.ManyToManyField(blank=True, to='drive.tag'),
        ),
        migrations.CreateModel(
            name='ZipFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveBigIntegerField(help_text='Size of the precompressed zipped file in bytes')),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('DELETED', 'Deleted'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10)),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloaded_folder', to='drive.node')),
            ],
        ),
        migrations.AddConstraint(
            model_name='nodeversion',
            constraint=models.UniqueConstraint(fields=('node', 'version_number'), name='unique_node_version'),
        ),
        migrations.AddConstraint(
            model_name='nodeversion',
            constraint=models.UniqueConstraint(fields=('storage_provider', 'storage_key'), name='unique_file_place'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='drive_node_search__0d9424_gin'),
        ),
    ]
